### ISSUE TITLE
Vue app build is crashing on loading CSV file more than 6 MB with the options set to true

### ISSUE THREAD

**Issue by UtkarshGupta-CS** [theplatapi/csv-loader#22]
## Issue Description
- Vue app build is crashing on loading CSV file more than 6 MB with the options set to true

## Webpack Config

```
module.exports = {
  chainWebpack: config => {
    config.module
      .rule("csv")
      .test(/\.csv$/)
      .use("csv-loader")
      .loader("csv-loader")
      .options({
        dynamicTyping: true,
        header: true,
        skipEmptyLines: true
      })
      .end();
  }
};
```

## Error
![image](https://user-images.githubusercontent.com/20434874/46094135-cfe73b80-c1d6-11e8-92be-fe95ccc7b127.png)

**Comment by UtkarshGupta-CS** [comment]
It works when no options are set to true.

**Comment by theplatapi** [comment]
Is the problem reproducible if you use PapaParse directly? If so then you hav to open the issue with them. This loader is just a wrapper around PapaParse.

**Comment by UtkarshGupta-CS** [comment]
Thanks for the quick response. I'll try to reproduce this problem with `papaparse` directly.  If it is working with `papaparse` than I'll reopen this issue otherwise open the same in there repo.
