### ISSUE TITLE
lower file sizes by keeping keys and values seperate in source

### ISSUE THREAD

**Issue by fin** [theplatapi/csv-loader#26]
hi there!

I created a fork at https://github.com/fin/csv-loader-small which keeps the keys and values separate, to avoid huge increases in file sizes because of the difference between CSV and JSON structures.
(it currently depends on node>11 due to my lazy use of `.flat()` but I could work around that)

Would you be interested in having this as an optional encoding method in this library? I could probably whip together a pull request, if you're into it.

best
-f

**Comment by njordhov** [comment]
How does this differ from setting `options.header: false`?

**Comment by theplatapi** [comment]
I want to keep this as a thin wrapper around Papa Parse. So if `options.header: false` works then use that. If it doesn't then petition the Papa Parse project to add the feature.
