### ISSUE TITLE
Publish v3.0.3 to npm

### ISSUE THREAD

**Issue by wyattades** [theplatapi/csv-loader#33]
Hey @theplatapi, it looks like this repository is on v3.0.3, but npm only has v3.0.2, can you please publish the latest version?

I ask because `papaparse` is still listed in `devDependencies` in v3.0.2, when it should be in `dependencies` or `peerDependencies`. Thanks!

**Comment by AlexChesters** [comment]
@theplatapi is it possible for the above to be completed? Currently the latest `csv-loader` doesn't work as `papaparse` isn't included as a production dependency

**Comment by theplatapi** [comment]
The newest version is now published. I made a github action to do this so updating is now easier.
